---
- hosts: localhost
  gather_facts: yes
  vars:
    image_tags: "{{ version | default('latest') }}"
    project_name: "{{ project_name }}"
    workspace: "{{ workspace }}"
  tasks:
    - name: Build the project using maven
      with_maven:
        executable: mvn
        goals: clean install
        project_file: "{{ workspace }}/pom.xml"
        settings_file: "{{ workspace }}/settings.xml"
      args:
        chdir: "{{ workspace }}"
    # - name: Build the docker image
    #   command: /usr/local/bin/docker build -t kimleangsrd/config-server .
    #   args:
    #     chdir: "{{ workspace }}"
    # - name: Login to registry
    #   docker_login:
    #     registry: https://index.docker.io/v1/
    #     username: "{{ docker_username }}"
    #     password: "{{ docker_password }}"
    #     reauthorize: yes
