---
- hosts: localhost
  gather_facts: yes
  vars:
    project_name: "{{ project_name }}"
    service_name: "{{ service_name }}"
    workspace: "{{ workspace }}"
    registry: "{{ registry }}"
    image_tags: "{{ version | default('latest') }}"
    docker_username: "{{ docker_username }}"
    docker_password: "{{ docker_password }}"
  tasks:
    - name: Login to registry
      community.docker.docker_login:
        username: "{{ docker_username }}"
        password: "{{ docker_password }}"
        reauthorize: yes

    - name: Echo workspace var
      ansible.builtin.debug:
        msg: "{{ workspace }}"

    - name: Create a network
      community.docker.docker_network:
        name: "{{ project_name }}"
        state: present

    - name: Copy the Global ENV file
      ansible.builtin.copy:
        remote_src: yes
        src: "{{ workspace }}/DevOps-Deployment/jenkins/ansible/env/_global.env"
        dest: "{{ workspace }}/_global.env"

    - name: Start Config-Server API
      community.docker.docker_container:
        name: "{{ service_name }}"
        image: "{{ registry }}:{{ image_tags }}"
        state: started
        restart_policy: always
        networks:
          - name: "{{ project_name }}"
        env_file: "{{ workspace }}/_global.env"

    # - name: Add a container to a network and leaving existing containers connected
    #   community.docker.docker_network:
    #     name: "{{ service_name }}"
    #     connected:
    #       - "{{ service_name }}"
    #     appends: true
