# consul-server.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consul
      component: server
  template:
    metadata:
      labels:
        app: consul
        component: server
    spec:
      containers:
        - name: consul
          image: hashicorp/consul:latest
          command: [ "consul", "agent", "-config-dir=/consul/config" ]
          ports:
            - containerPort: 8500
              name: http
            - containerPort: 8600
              name: dns
          volumeMounts:
            - name: config
              mountPath: /consul/config
            - name: data
              mountPath: /consul/data
      volumes:
        - name: config
          configMap:
            name: consul-config
        - name: data
          emptyDir: { }

---
apiVersion: v1
kind: Service
metadata:
  name: consul-server
spec:
  ports:
    - port: 8500
      targetPort: 8500
      name: http
    - port: 8600
      targetPort: 8600
      name: dns
  selector:
    app: consul
    component: server
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: consul-ui
spec:
  type: LoadBalancer
  ports:
    - port: 8500
      targetPort: 8500
  selector:
    app: consul
    component: server
