apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      containers:
        - name: kafka-ui
          image: provectuslabs/kafka-ui:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          env:
            - name: KAFKA_CLUSTERS_NAME
              valueFrom:
                configMapKeyRef:
                  key: KAFKA_CLUSTERS_NAME
                  name: kafka-ui-configmap
            - name: KAFKA_CLUSTERS_BOOTSTRAPSERVERS
              valueFrom:
                configMapKeyRef:
                  key: KAFKA_CLUSTERS_BOOTSTRAPSERVERS
                  name: kafka-ui-configmap
            - name: DYNAMIC_CONFIG_ENABLED
              valueFrom:
                configMapKeyRef:
                  key: DYNAMIC_CONFIG_ENABLED
                  name: kafka-ui-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-ui
spec:
  selector:
    app: kafka-ui
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8080
  sessionAffinity: None
  type: LoadBalancer