apiVersion: apps/v1
kind: Deployment
metadata:
  name: schema-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schema-registry
  template:
    metadata:
      labels:
        app: schema-registry
    spec:
      enableServiceLinks: false
      containers:
      - name: schema-registry
        image: confluentinc/cp-schema-registry:latest
        ports:
        - containerPort: 8081
          name: schema-registry
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
        env:
        - name: SCHEMA_REGISTRY_HOST_NAME
          valueFrom:
            configMapKeyRef:
              key: SCHEMA_REGISTRY_HOST_NAME
              name: schema-registry-configmap
        - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              key: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
              name: schema-registry-configmap
        - name: SCHEMA_REGISTRY_LISTENERS
          valueFrom:
            configMapKeyRef:
              key: SCHEMA_REGISTRY_LISTENERS
              name: schema-registry-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: schema-registry
spec:
  selector:
    app: schema-registry
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      name: schema-registry