global:
  scrape_interval: 2s
  evaluation_interval: 2s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]
rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: "Gateway-Service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8080"]
        labels:
          application: Gateway-Service

  - job_name: "Auth-Service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8888"]
        labels:
          application: "Auth-Service"

  - job_name: "Chat-Service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:9990"]
        labels:
          application: Chat-Service

  - job_name: 'Content-Service'
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:9991"] # Not good in production
        labels:
          application: Content-Service

  - job_name: 'Setting-Service'
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:9992"] # Not good in production
        labels:
          application: Setting-Service

  - job_name: 'Discovery-Service'
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8761"] # Not good in production
        labels:
          application: Discovery-Service
  
  - job_name: 'Mail-Service'
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:9995"] # Not good in production
        labels:
          application: Mail-Service

  - job_name: 'Config-Server'
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:9999"] # Not good in production
        labels:
          application: Config-Server