apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-auth-pv
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/postgres-auth"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-auth-pvc
spec:
  storageClassName: manual
  volumeName: postgres-auth-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi