# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: tempo-pv
#   labels:
#     type: local
#     app: tempo
# spec:
#   storageClassName: manual
#   persistentVolumeReclaimPolicy: Retain
#   capacity:
#     storage: 1Gi
#   accessModes:
#     - ReadWriteMany
#   hostPath:
#     path: "/tmp/tempo"
# ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tempo-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi