apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: kimleangsrd/config-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9999
          resources:
            requests:
              cpu: 10m
              memory: 500Mi
          envFrom:
            - configMapRef:
                name: common-config