apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-configmap
  labels:
    app: logstash
data:
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
      
    }
    output {
      elasticsearch {
        hosts => ["http://${ELASTICSEARCH_HOST}"]
        index => "logstash-%{+YYYY.MM.dd}"
      }
      stdout { codec => rubydebug }
    }
