apiVersion: v1
kind: ConfigMap
metadata:
  name: schema-registry-configmap
data:
  SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "broker:29092"
  SCHEMA_REGISTRY_HOST_NAME: "schema-registry"
  SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:8081"